export enum ICON_NAMES {
  logo = 'logo',
  white_logo = 'white_logo',

  slider_img1 = 'slider_img1',
  slider_img2 = 'slider_img2',
  slider_img3 = 'slider_img3',
  slider_img4 = 'slider_img4',

  design_no_limit = 'design_no_limit',
  expert_craft = 'expert_craft',
  superior_qauality = 'superior_qauality',
  unsurpassed_value = 'unsurpassed_value',
  woman_carpenter = 'woman_carpenter',
  credit_card = 'credit_card',
  delivery = 'delivery',
  kitchen_design = 'kitchen_design',
  roulette = 'roulette',
  woodmaker = 'woodmaker',
  calculator = 'calculator',

  portfolio_slide_1_1 = 'portfolio_slide_1_1',
  portfolio_slide_1_2 = 'portfolio_slide_1_2',
  portfolio_slide_1_3 = 'portfolio_slide_1_3',
  portfolio_slide_1_4 = 'portfolio_slide_1_4',

  photo_block_1 = 'photo_block_1',
  photo_block_2 = 'photo_block_2',
  photo_block_3 = 'photo_block_3',
  photo_block_4 = 'photo_block_4',
  photo_block_5 = 'photo_block_5',
  photo_block_6 = 'photo_block_6',
  photo_block_7 = 'photo_block_7',
  photo_block_8 = 'photo_block_8',

  cross = 'cross',
  check = 'check',

  our_producrtion_1 = 'our_producrtion_1',
  our_producrtion_2 = 'our_producrtion_2',
  our_producrtion_3 = 'our_producrtion_3',
  our_producrtion_4 = 'our_producrtion_4',

  review_icon_1 = 'review_icon_1',
  review_icon_2 = 'review_icon_2',

  burger = 'burger',

  about_us_photo = 'about_us_photo',
  faq_img = 'faq_img',
  phone = 'phone',
  mail = 'mail',

  bathroom_vanities = 'bathroom_vanities',
  cabinet_doors = 'cabinet_doors',
  cabinet_finishing = 'cabinet_finishing',
  kitchen_cabinets = 'kitchen_cabinets',
  polities_and_terms = 'polities_and_terms',
  specialty_islands = 'specialty_islands',
  wood_species = 'wood_species',

  bottom_drawer = 'bottom_drawer',
  cabinet_toe_kick = 'cabinet_toe_kick',
  close_hingles = 'close_hingles',
  dovetailde_drawers = 'dovetailde_drawers',
  plywood_shell = 'plywood_shell',
  storage_trays = 'storage_trays',
  top_row_drawers = 'top_row_drawers',
  wood_face_frames = 'wood_face_frames',

  base_cabinets = 'base_cabinets',
  corner_base = 'corner_base',
  corner_wall = 'corner_wall',
  pantry_cabinets = 'pantry_cabinets',
  wall_cabinets = 'wall_cabinets',

  matching_crown = 'matching_crown',
  post_corners = 'post_corners',
  raised_panel_end = 'raised_panel_end',

  pure_bond = 'pure_bond',
  click_prices = 'click_prices',
  request_quote = 'request_quote',

  specialty_islands_main_img = 'specialty_islands_main_img',
  specialty_islands_bakeware = 'specialty_islands_bakeware',
  specialty_islands_corner_base_cabinets = 'specialty_islands_corner_base_cabinets',
  specialty_islands_corner_cabinets = 'specialty_islands_corner_cabinets',
  specialty_islands_cutting_board = 'specialty_islands_cutting_board',
  specialty_islands_flatware = 'specialty_islands_flatware',
  specialty_islands_inset_cabinets = 'specialty_islands_inset_cabinets',
  specialty_islands_lazy_super_susan = 'specialty_islands_lazy_super_susan',
  specialty_islands_microwave_cabinets = 'specialty_islands_microwave_cabinets',
  specialty_islands_pantry_cabinets = 'specialty_islands_pantry_cabinets',
  specialty_islands_pot_pan = 'specialty_islands_pot_pan',
  specialty_islands_reach_corner_cabinets = 'specialty_islands_reach_corner_cabinets',
  specialty_islands_shelf_base_cabinet = 'specialty_islands_shelf_base_cabinet',
  specialty_islands_spice_sundry = 'specialty_islands_spice_sundry',
  specialty_islands_waste = 'specialty_islands_waste',

  bathroom_img = 'bathroom_img',
  bathroom_cabinet = 'bathroom_cabinet',
  furniture_post_corners = 'furniture_post_corners',

  cabinet_doors_preview = 'cabinet_doors_preview',
  door_catalog_example1 = 'door_catalog_example1',
  door_catalog_example2 = 'door_catalog_example2',
  door_catalog_example3 = 'door_catalog_example3',

  general_door = 'general_door',

  inner_edge_profile1 = 'inner_edge_profile1',
  inner_edge_profile2 = 'inner_edge_profile2',
  inner_edge_profile3 = 'inner_edge_profile3',
  inner_edge_profile4 = 'inner_edge_profile4',

  outer_edge_profile1 = 'outer_edge_profile1',
  outer_edge_profile2 = 'outer_edge_profile2',
  outer_edge_profile3 = 'outer_edge_profile3',
  outer_edge_profile4 = 'outer_edge_profile4',

  raised_panel_profile1 = 'raised_panel_profile1',
  raised_panel_profile2 = 'raised_panel_profile2',
  raised_panel_profile3 = 'raised_panel_profile3',
  raised_panel_profile4 = 'raised_panel_profile4',

  df_flat_panel = 'df_flat_panel',
  df_raised_panel = 'df_raised_panel',
  df_shaker = 'df_shaker',
  df_slab_profile_edge = 'df_slab_profile_edge',

  fp_arch_top = 'fp_arch_top',
  fp_cathedral_arch = 'fp_cathedral_arch',
  fp_double_arch = 'fp_double_arch',
  fp_double_cathedral_arch = 'fp_double_cathedral_arch',
  fp_square_beaded_panel = 'fp_square_beaded_panel',
  fp_square_top = 'fp_square_top',

  rp_arch_top = 'rp_arch_top',
  rp_cathedral_arch = 'rp_cathedral_arch',
  rp_double_arch = 'rp_double_arch',
  rp_double_cathedral_arch = 'rp_double_cathedral_arch',
  rp_square_top = 'rp_square_top',

  sd_shaker_beaded_panel = 'sd_shaker_beaded_panel',
  sd_shaker_side_by_side = 'sd_shaker_side_by_side',
  sd_shaker_square = 'sd_shaker_square',

  door_drawers_available1 = 'door_drawers_available1',
  door_drawers_available2 = 'door_drawers_available2',

  cabinet_finishing_preview = 'cabinet_finishing_preview',

  cf_preview_natural_clear_coat_img = 'cf_preview_natural_clear_coat_img',
  cf_preview_painted_glaze_img = 'cf_preview_painted_glaze_img',
  cf_preview_painted_img = 'cf_preview_painted_img',
  cf_preview_stainded_clear_coat_img = 'cf_preview_stainded_clear_coat_img',
  cf_preview_unfinished_img = 'cf_preview_unfinished_img',

  maple_acres = 'maple_acres',
  maple_asbury = 'maple_asbury',
  maple_baywood = 'maple_baywood',
  maple_chocolatespice = 'maple_chocolatespice',
  maple_coffee = 'maple_coffee',
  maple_darkknight = 'maple_darkknight',
  maple_ebony = 'maple_ebony',
  maple_goldenbrown = 'maple_goldenbrown',
  maple_kona = 'maple_kona',
  maple_malaguania = 'maple_malaguania',
  maple_newcarrington = 'maple_newcarrington',
  maple_nutmeg = 'maple_nutmeg',
  maple_onyx = 'maple_onyx',
  maple_richtobacco = 'maple_richtobacco',
  maple_sealy = 'maple_sealy',
  maple_wheat = 'maple_wheat',

  glaze_finishes_wambrownglaze = 'glaze_finishes_wambrownglaze',
  glaze_finishes_blackwarmbrown = 'glaze_finishes_blackwarmbrown',
  glaze_finishes_chelseagrey = 'glaze_finishes_chelseagrey',
  glaze_finishes_georgianbrown = 'glaze_finishes_georgianbrown',
  glaze_finishes_metropolitan_portabella = 'glaze_finishes_metropolitan_portabella',
  glaze_finishes_pearlearly = 'glaze_finishes_pearlearly',

  cherry_acres = 'cherry_acres',
  cherry_baywood = 'cherry_baywood',
  cherry_boston = 'cherry_boston',
  cherry_chestnut = 'cherry_chestnut',
  cherry_chocolatespice = 'cherry_chocolatespice',
  cherry_coffee = 'cherry_coffee',
  cherry_ebony = 'cherry_ebony',
  cherry_kona = 'cherry_kona',
  cherry_malaguania = 'cherry_malaguania',
  cherry_newcarrington = 'cherry_newcarrington',
  cherry_richtobacco = 'cherry_richtobacco',
  cherry_saddle = 'cherry_saddle',
  cherry_sealy = 'cherry_sealy',
  cherry_tawny = 'cherry_tawny',
  cherry_washingtoncherry = 'cherry_washingtoncherry',
  cherry_windsor = 'cherry_windsor',

  paint_finishes_antiquewhite = 'paint_finishes_antiquewhite',
  paint_finishes_black = 'paint_finishes_black',
  paint_finishes_celery = 'paint_finishes_celery',
  paint_finishes_chelseagrey = 'paint_finishes_chelseagrey',
  paint_finishes_countrywhite = 'paint_finishes_countrywhite',
  paint_finishes_decoratorwhite = 'paint_finishes_decoratorwhite',
  paint_finishes_georgian = 'paint_finishes_georgian',
  paint_finishes_glacier = 'paint_finishes_glacier',
  paint_finishes_metropolitan = 'paint_finishes_metropolitan',
  paint_finishes_millingtongold = 'paint_finishes_millingtongold',
  paint_finishes_pandawhite = 'paint_finishes_pandawhite',
  paint_finishes_pearl = 'paint_finishes_pearl',
  paint_finishes_regalblue = 'paint_finishes_regalblue',
  paint_finishes_sanddollar = 'paint_finishes_sanddollar',
  paint_finishes_skygrey = 'paint_finishes_skygrey',
  paint_finishes_white = 'paint_finishes_white',

  quarter_sawn_asbury = 'quarter_sawn_asbury',
  quarter_sawn_briar = 'quarter_sawn_briar',
  quarter_sawn_copper = 'quarter_sawn_copper',
  quarter_sawn_darknight = 'quarter_sawn_darknight',
  quarter_sawn_driftwood = 'quarter_sawn_driftwood',
  quarter_sawn_goldenbrown = 'quarter_sawn_goldenbrown',
  quarter_sawn_liteasbury = 'quarter_sawn_liteasbury',
  quarter_sawn_michaelscherry = 'quarter_sawn_michaelscherry',
  quarter_sawn_onyx = 'quarter_sawn_onyx',
  quarter_sawn_sealy = 'quarter_sawn_sealy',
  quarter_sawn_sierra = 'quarter_sawn_sierra',
  quarter_sawn_smokehouse = 'quarter_sawn_smokehouse',
  quarter_sawn_stormgrey = 'quarter_sawn_stormgrey',
  quarter_sawn_tanbark = 'quarter_sawn_tanbark',
  quarter_sawn_tavern = 'quarter_sawn_tavern',
  quarter_sawn_tea = 'quarter_sawn_tea',

  red_oak_acorn = 'red_oak_acorn',
  red_oak_acres = 'red_oak_acres',
  red_oak_coffee = 'red_oak_coffee',
  red_oak_copper = 'red_oak_copper',
  red_oak_ebony = 'red_oak_ebony',
  red_oak_goldenhoney = 'red_oak_goldenhoney',
  red_oak_kona = 'red_oak_kona',
  red_oak_malaguania = 'red_oak_malaguania',
  red_oak_newcarrington = 'red_oak_newcarrington',
  red_oak_onyx = 'red_oak_onyx',
  red_oak_pewter = 'red_oak_pewter',
  red_oak_richtobacco = 'red_oak_richtobacco',
  red_oak_saddle = 'red_oak_saddle',
  red_oak_sealy = 'red_oak_sealy',
  red_oak_tawny = 'red_oak_tawny',
  red_oak_wheat = 'red_oak_wheat',

  wood_species_preview_img = 'wood_species_preview_img',
  wood_species_alder = 'wood_species_alder',
  wood_species_cherry = 'wood_species_cherry',
  wood_species_hickory = 'wood_species_hickory',
  wood_species_knotty_alder = 'wood_species_knotty_alder',
  wood_species_maple = 'wood_species_maple',
  wood_species_poplar = 'wood_species_poplar',
  wood_species_quarter_sawn = 'wood_species_quarter_sawn',
  wood_species_red_oak = 'wood_species_red_oak',
  wood_species_rustic_hickory = 'wood_species_rustic_hickory',
  wood_species_walnut = 'wood_species_walnut',
  wood_species_white_oak = 'wood_species_white_oak',
  wood_species_wormy_maple = 'wood_species_wormy_maple',

  policies_and_terms1 = 'policies_and_terms1',
  policies_and_terms2 = 'policies_and_terms2',

  base_cabinet_length = 'base_cabinet_length',
  pantry_cabinet_length = 'pantry_cabinet_length',
  wall_cabinet_length = 'wall_cabinet_length',

  corner_cabinets_base = 'corner_cabinets_base',
  corner_cabinets_wall = 'corner_cabinets_wall',

  fpa_arch_top = 'fpa_arch_top',
  fpa_square = 'fpa_square',
  fpad_double_arch = 'fpad_double_arch',
  fpb_beaded_panel = 'fpb_beaded_panel',
  fpc_cathedral_arch = 'fpc_cathedral_arch',
  fpcd_double_cathedral_arch = 'fpcd_double_cathedral_arch',

  rpa_raised_arch_top = 'rpa_raised_arch_top',
  rpad_raised_double_arch = 'rpad_raised_double_arch',
  rpc_raised_cathedral_arch = 'rpc_raised_cathedral_arch',
  rpcd_raised_double_cathedral_arch = 'rpcd_raised_double_cathedral_arch',
  rps_raised_square = 'rps_raised_square',

  spb_shaker_beaded_panel = 'spb_shaker_beaded_panel',
  sss_split_shaker = 'sss_split_shaker',
  sst_shaker = 'sst_shaker',

  quote_multiply_finishes = 'quote_multiply_finishes',
}

export type IconNames = keyof typeof ICON_NAMES;
